//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Volunteers.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Join
    {
        public long ID { get; set; }
        public Nullable<long> Round_Volunteer_ID { get; set; }
        public Nullable<long> Volunteers_ID { get; set; }
        public string Rolename { get; set; }
    
        public virtual Round_Volunteer Round_Volunteer { get; set; }
        public virtual Volunteer Volunteer { get; set; }
    }
}
