//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Volunteers.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public long ID { get; set; }
        public Nullable<long> Round_Volunteer_ID { get; set; }
        public string Standard_1 { get; set; }
        public string Standard_2 { get; set; }
        public string Standard_3 { get; set; }
        public Nullable<int> Point { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Round_Volunteer Round_Volunteer { get; set; }
    }
}
