//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Volunteers.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Round_Volunteer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Round_Volunteer()
        {
            this.Material_Support = new HashSet<Material_Support>();
            this.People = new HashSet<Person>();
            this.Joins = new HashSet<Join>();
            this.Reviews = new HashSet<Review>();
        }
    
        public long ID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Place { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Register { get; set; }
        public Nullable<long> Journey_ID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Dealine_Register { get; set; }
        public Nullable<int> MinPeople { get; set; }
        public Nullable<int> MaxPeople { get; set; }
        public string ReasonCancer { get; set; }
        public string ReasonNotTest { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<long> Volunteers_ID { get; set; }
    
        public virtual Journey Journey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material_Support> Material_Support { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> People { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Join> Joins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual Volunteer Volunteer { get; set; }
    }
}
